trigger:
- main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Building the application...
  displayName: 'Building the application'

- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: |
      **\*Test*.py
    searchFolder: '$(System.DefaultWorkingDirectory)'

- script: echo Publishing the packaged application...
  displayName: 'Publishing the packaged application'
  env:
    PackageLocation: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(PackageLocation)'
    ArtifactName: 'packaged-application'
    publishLocation: 'Container'