trigger:
- master
pool:
  vmImage: 'windows-latest'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true
- script: |
    echo "Building the application..."
    rem Custom tasks to build the application
    rem For example:
    rem /p:WebPublishMethod=Package
    rem /p:PackageLocation="$(build.artifactStagingDirectory)"
  displayName: 'Build application'
- task: VSTest@2
  displayName: 'Run unit tests'
- script: |
    echo "Packaging the application..."
    rem Custom task to package the built application
    rem For example:
    rem /p:WebPublishMethod=Package
    rem /p:PackageLocation="$(build.artifactStagingDirectory)"
  displayName: 'Package application'
- task: VSTest@2
  displayName: 'Run UNIT Test'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'packaged-application'
    publishLocation: 'Container'









