trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'  # Specifying a major version only, e.g., 3.x, to avoid compatibility issues
    addToPath: true

- script: |
    echo "Building the application..."
    # Custom tasks to build the application
    # For example:
    # /p:WebPublishMethod=Package
    # /p:PackageLocation="$(build.artifactStagingDirectory)"
  displayName: 'Build application'

- task: VSTest@2
  displayName: 'Run unit tests'

- script: |
    echo "Packaging the application..."
    # Custom task to package the built application
    # For example:
    # /p:WebPublishMethod=Package
    # /p:PackageLocation="$(build.artifactStagingDirectory)"
  displayName: 'Package application'

- task: VSTest@2
  displayName: 'Run UNIT Test'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'packaged-application'
    publishLocation: 'Container'
