trigger:
  - main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: InstallDependencies
        displayName: 'Install Dependencies'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
          - script: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
            displayName: 'Install dependencies'
            continueOnError: true  # Continue if there are errors during installation

      - job: RunUnitTests
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true
          - script: |
              python -m unittest discover -s tests -p '*_test.py'
            displayName: 'Run unit tests'

  - stage: Publish
    displayName: 'Publish Artifacts'
    jobs:
      - job: PublishArtifacts
        displayName: 'Publish Build Artifacts'
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)/path/to/artifacts'
              artifactName: 'package'
