trigger:
  branches:
    include:
      - main
jobs:
- job: Build_and_Test
  displayName: 'Build Application and Test by using Unit tests'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12' # Use Python 3.12
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'
  - script: |
      if [ -d "tests" ] && [ -n "$(find tests -type f -name '*_test.py')" ]; then
        python -m unittest discover -s tests -p '*_test.py'
      else
        echo "No test files found. Skipping test execution."
      fi
    displayName: 'Run unit tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/pytest.xml'
      testRunTitle: 'Unit Tests'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)'
      artifactName: 'build_output'
