trigger:
- main
pool:
  vmImage: 'windows-latest'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true
- script: |
    echo "Building the application..."
    REM Add custom build commands here
  displayName: 'Build application'
- script: |
    echo "Running unit tests..."
    python test_notebook.py  # Execute the test file
  displayName: 'Run unit tests'
- script: |
    echo "Packaging the application..."
    REM Add custom packaging commands here
  displayName: 'Package application'
- task: VSTest@2
  displayName: 'Run UNIT Test'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'packaged-application'
    publishLocation: 'Container'
