trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet
  displayName: 'Use .NET SDK'

- script: |
    echo "Building the application..."
    dotnet build YourProjectName.csproj /p:WebPublishMethod=Package /p:PackageLocation="$(build.artifactStagingDirectory)"
  displayName: 'Build application'

- task: VSTest@2
  displayName: 'Run unit tests'

- script: |
    echo "Packaging the application..."
    dotnet publish YourProjectName.csproj -c Release -o $(build.artifactStagingDirectory)
  displayName: 'Package application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'packaged-application'
    publishLocation: 'Container'
