trigger:
  - main  # Adjust the branch name as needed

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: InstallDependencies
        displayName: 'Install Dependencies'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
              addToPath: true
          - script: |
              python -m pip install --upgrade pip
              python -m pip install -r requirements.txt
            displayName: 'Install dependencies'
            continueOnError: true  # Continue if there are errors during installation

  - stage: RunUnitTests
    displayName: 'Run Unit Tests'
    jobs:
      - job: RunUnitTests
        displayName: 'Run Unit Tests'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.9'
              addToPath: true
          - script: |
              python -m unittest discover -s $(Build.SourcesDirectory) -p '*_unit.py'
            displayName: 'Run unit tests'

  - stage: Publish
    displayName: 'Publish Artifacts'
    dependsOn: RunUnitTests   # Depends on the RunUnitTests stage
    condition: succeeded('RunUnitTests')  # Run this stage only if RunUnitTests job succeeds
    jobs:
      - job: PublishArtifacts
        displayName: 'Publish Build Artifacts'
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)'
              artifactName: 'package'
