trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
  displayName: 'Upgrade pip and install dependencies'

- script: |
    echo "No build step required for Python projects."
  displayName: 'Build application'

- script: |
    pytest
  displayName: 'Run unit tests'

- script: |
    echo "No packaging step required for Python projects."
  displayName: 'Package application'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish artifacts'
