# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


trigger:
- main  # Adjust this to your branch or trigger configuration

pool:
  vmImage: 'windows-latest'  # Use a Windows agent for .NET application builds

steps:
- task: MSBuild@1
  inputs:
    solution: 'path/to/your/solution.sln'
    msbuildArgs: '/p:WebPublishMethod=Package /p:PackageLocation="$(build.artifactStagingDirectory)"'

- task: VSTest@2
  inputs:
    platform: 'Any CPU'
    configuration: 'Release'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
     
    