trigger:
- main  # Adjust the branch name if needed

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: 'python -m pip install --upgrade pip'
  displayName: 'Install pip'

- script: 'pip install -r requirements.txt'
  displayName: 'Install dependencies'

- script: 'python -m unittest discover -s tests'
  displayName: 'Run unit tests'

- script: 'python setup.py sdist --formats=gztar -d "$(Build.ArtifactStagingDirectory)"'
  displayName: 'Package the built application'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'miningequipment'
    publishLocation: 'Container'
