trigger:
- master
pool:
  vmImage: 'windows-latest'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true
- script: |
    echo "Building the application..."
    # Add commands to build the application and generate artifacts
    # For example:
    # python build_script.py
    # mkdir $(System.DefaultWorkingDirectory)/artifacts
    # cp generated_artifacts $(System.DefaultWorkingDirectory)/artifacts
  displayName: 'Build application'
- task: VSTest@2
  displayName: 'Run unit tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Data_Mining\tests.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
- script: |
    echo "Packaging the application..."
    rem Custom task to package the built application
    rem For example:
    rem /p:WebPublishMethod=Package
    rem /p:PackageLocation="$(System.DefaultWorkingDirectory)/artifacts"
  displayName: 'Package application'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(System.DefaultWorkingDirectory)/artifacts'
    artifactName: 'packaged-application'
    publishLocation: 'Container'