trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    echo "Installing dependencies..."
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    echo "Running unit tests..."
    python -m pytest
  displayName: 'Run unit tests'

- script: |
    echo "Packaging the application..."
    # Perform any packaging steps here, such as copying files to an artifact staging directory
    mkdir -p $(build.artifactStagingDirectory)/packaged-application
    cp -r ./* $(build.artifactStagingDirectory)/packaged-application
  displayName: 'Package application'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/packaged-application'
    artifactName: 'packaged-application'
    publishLocation: 'Container'

